<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise</title>
    <style>
        body {
            background-color: #414141;
            color: #fff;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Three states of Promise</h1>
        <h3>pending: initial state, neither fulfilled nor rejected.</h3>
        <h3>fulfilled: meaning that the operation was completed successfully.</h3>
        <h3>rejected: meaning that the operation failed</h3>
    </div>
</body>
<script>
    // Promise is a JavaScript object for asynchronous operation.
    // Creating a new promise object
    const promiseOne = new Promise(function(resolve, reject) {
        // Do an async task
        // DB calls, cryptography, network calls
        setTimeout(function () {
            console.log('Async task1 done');
            resolve(); // resolve() is called to execute the .then() method
        }, 1000)
    });
    // Consuming the promise
    promiseOne.then(function() {
        console.log('promiseOne is cosumed');
    });

    // Without storing the promise in an variable
    new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Async task2 done');
            resolve()
        }, 1000)
    }).then (() => console.log('promiseTwo is consumed'));


    // Passing object to resolve
    const promiseThree = new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Async task3 done');
            resolve({ username: 'Ronik', email: 'ronik@example.com'});
        }, 1000);
    });

    promiseThree.then((user) => {
        console.log(user);
        console.log(user.username);
        console.log('promiseThree is consumed');
    })


    // promise chaining -> used for database connection, network calls, etc
    const promiseFour = new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('Async task4 done');
            let error = false;
            if (!error) {
                resolve({ username: 'Ronik', email: 'ronik@example.com'});
            } else {
                reject('ERROR: Some went wrong');
            }
        }, 1000);
    })
    // Promise {<pending>} -> promise is not consumed
    // const username = promiseFour.then((user) => {
    //     console.log(user);
    //     return user.username;
    // });
    // console.log(username);

    // Here the first .then() method returns the value/object/parameter to the 2nd .then() method and so on
    promiseFour.then((user) => {
        console.log(user)
        return user.username;
    })
    .then((username) => {
        // console.log('Username:',username) // Username: Ronik
        console.log(`Username: ${username}`); // Username: Ronik
    })
    .catch((error) => console.log(error))
    .finally(() => console.log('promiseFour is either consumed or rejected'));

    
    // async & await -> another way to consume/handle promise
    const promiseFive = new Promise(function(resolve, reject) {
        setTimeout(() => {
            let error = true;
            if (!error) {
                console.log('Async task5 done');
                resolve({ username: 'JavaScript', password: '123'});
            } else {
                reject('ERROR: JS went wrong');
            }
        }, 1000);
    });

    // handling the above promise using async & await
    // It is not capable of error handling so to solve this program we use try-catch block, finally block can also be used here
    async function consumePromiseFive () {
        try{
            const user = await promiseFive;
            console.log(user);
            console.log(`Username: ${user.username}`);
            console.log('promiseFive is consumed');
        } catch (error) {
            console.log(error);
        } finally {
            console.log('promiseFive is either consumed or rejected');
        }
    }
    // as async function is a special kind of function, so it is needed to be called, whereas .then() method is not needed to be called
    consumePromiseFive();


// Fetch() API
// Handling it using async & await
    // async function getAllUsers () {
    //     try {
    //         const response = await fetch('https://jsonplaceholder.typicode.com/users');
    //         const data = await response.json();
    //         console.log(response);
    //         console.log(data);
    //     } catch (error) {
    //         console.log(error);
    //     }
    // }

    // getAllUsers();

// Handling same promise using .then() method

    fetch('https://jsonplaceholder.typicode.com/users')
    .then((response) => {
        console.log("Response: ",response);
        return response.json()
    })
    .then((data) => console.log("Data: ", data))
    .catch((error) => console.log(error))

    // const response = fetch('https://jsonplaceholder.typicode.com/users')
    // response.then(function (user) {
    //     const data = user.json(); // Here user.json() returns a promise & requires another.then() method to consume it
    //     console.log(data);
    // })
    // .catch(function (error) {
    //     console.log(error);
    // })

    // fetch('https://jsonplaceholder.typicode.com/users')
    // .then(function (user) {
    //     const data = user.json(); // Here user.json() returns a promise & requires another.then() method to consume it
    //     console.log(data);
    // })
    // .catch(function (error) {
    //     console.log(error);
    // })

</script>
</html>